-- 계정 sup 생성
CREATE USER SUP
IDENTIFIED BY SUP
DEFAULT tablespace users
TEMPORARY tablespace temp;

ALTER USER SUP
DEFAULT tablespace USERS 
QUOTA UNLIMITED ON users;

GRANT resource, connect TO SUP;
GRANT CREATE TABLE TO SUP;
