/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.40
 * Generated at: 2020-12-23 13:41:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SpringHome/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sup/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1607490716187L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link\n");
      out.write("\thref=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-md-8\">\n");
      out.write("\t\t\t\t<h2 class=\"page-header\">Feed</h2>\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t<section class=\"comment-list\">\n");
      out.write("\t\t\t\t\t<!-- First Comment -->\n");
      out.write("\t\t\t\t\t<article class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-2 hidden-xs\">\n");
      out.write("\t\t\t\t\t\t\t<figure class=\"thumbnail\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-responsive\"\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"http://www.tangoflooring.ca/wp-content/uploads/2015/07/user-avatar-placeholder.png\" />\n");
      out.write("\t\t\t\t\t\t\t\t<figcaption class=\"text-center\">username</figcaption>\n");
      out.write("\t\t\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-10 col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default arrow left\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"text-left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"comment-user\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user\"></i>username\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<time class=\"comment-date\" datetime=\"16-12-2014 01:05\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>date\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</time>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"comment-post\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\telit, sed do eiusmod tempor incididunt ut labore et dolore\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmagna aliqua. Ut enim ad minim veniam, quis nostrud\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\texercitation ullamco laboris nisi ut aliquip ex ea commodo\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsequat.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/report\" class=\"btn btn-danger\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-reply\"></i> 신고하기</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\"><i class=\"fa fa-reply\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t좋아요</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t<!-- Second Comment Reply -->\n");
      out.write("\t\t\t\t\t<article class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-2 hidden-xs\">\n");
      out.write("\t\t\t\t\t\t\t<figure class=\"thumbnail\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-responsive\"\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"http://www.tangoflooring.ca/wp-content/uploads/2015/07/user-avatar-placeholder.png\" />\n");
      out.write("\t\t\t\t\t\t\t\t<figcaption class=\"text-center\">username</figcaption>\n");
      out.write("\t\t\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-10 col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default arrow left\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"text-left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"comment-user\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user\"></i>username\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<time class=\"comment-date\" datetime=\"16-12-2014 01:05\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>date\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</time>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"comment-post\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\telit, sed do eiusmod tempor incididunt ut labore et dolore\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmagna aliqua. Ut enim ad minim veniam, quis nostrud\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\texercitation ullamco laboris nisi ut aliquip ex ea commodo\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsequat.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/report\" class=\"btn btn-danger\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-reply\"></i> 신고하기</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\"><i class=\"fa fa-reply\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t좋아요</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t<!-- Third Comment -->\n");
      out.write("\t\t\t\t\t<article class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-10 col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default arrow right\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"comment-user\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user\"></i> That Guy\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<time class=\"comment-date\" datetime=\"16-12-2014 01:05\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i> Dec 16, 2014\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</time>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"comment-post\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\telit, sed do eiusmod tempor incididunt ut labore et dolore\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmagna aliqua. Ut enim ad minim veniam, quis nostrud\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\texercitation ullamco laboris nisi ut aliquip ex ea commodo\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsequat.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/report\" class=\"btn btn-danger\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-reply\"></i> 신고하기</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\"><i class=\"fa fa-reply\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t좋아요</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-2 hidden-xs\">\n");
      out.write("\t\t\t\t\t\t\t<figure class=\"thumbnail\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-responsive\"\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"http://www.tangoflooring.ca/wp-content/uploads/2015/07/user-avatar-placeholder.png\" />\n");
      out.write("\t\t\t\t\t\t\t\t<figcaption class=\"text-center\">username</figcaption>\n");
      out.write("\t\t\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t<!-- Fourth Comment -->\n");
      out.write("\t\t\t\t\t<article class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-2 hidden-xs\">\n");
      out.write("\t\t\t\t\t\t\t<figure class=\"thumbnail\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-responsive\"\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"http://www.tangoflooring.ca/wp-content/uploads/2015/07/user-avatar-placeholder.png\" />\n");
      out.write("\t\t\t\t\t\t\t\t<figcaption class=\"text-center\">username</figcaption>\n");
      out.write("\t\t\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-10 col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default arrow left\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"text-left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"comment-user\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user\"></i>username\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<time class=\"comment-date\" datetime=\"16-12-2014 01:05\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>date\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</time>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"comment-post\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\telit, sed do eiusmod tempor incididunt ut labore et dolore\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmagna aliqua. Ut enim ad minim veniam, quis nostrud\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\texercitation ullamco laboris nisi ut aliquip ex ea commodo\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsequat.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/report\" class=\"btn btn-danger\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-reply\"></i> 신고하기</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\"><i class=\"fa fa-reply\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t좋아요</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t<!-- Fifth Comment -->\n");
      out.write("\t\t\t\t\t<article class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-10 col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default arrow right\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"comment-user\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user\"></i> That Guy\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<time class=\"comment-date\" datetime=\"16-12-2014 01:05\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i> Dec 16, 2014\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</time>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"comment-post\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\telit, sed do eiusmod tempor incididunt ut labore et dolore\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmagna aliqua. Ut enim ad minim veniam, quis nostrud\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\texercitation ullamco laboris nisi ut aliquip ex ea commodo\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsequat.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/report\" class=\"btn btn-danger\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-reply\"></i> 신고하기</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\"><i class=\"fa fa-reply\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t좋아요</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-2 hidden-xs\">\n");
      out.write("\t\t\t\t\t\t\t<figure class=\"thumbnail\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-responsive\"\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"http://www.tangoflooring.ca/wp-content/uploads/2015/07/user-avatar-placeholder.png\" />\n");
      out.write("\t\t\t\t\t\t\t\t<figcaption class=\"text-center\">username</figcaption>\n");
      out.write("\t\t\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</article>\n");
      out.write("\n");
      out.write("\t\t\t\t</section>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(4,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("common/header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(24,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<h1>no session</h1>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/index.jsp(27,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<h1>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h1>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/index.jsp(234,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("common/footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
